version: '3.8'

services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - influxdb
    ports:
      - "8000:8000"  # API
      - "8888:8888"  # Jupyter
    networks:
      - trading_network

  redis:
    image: redis:7-alpine
    container_name: trading_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - trading_network

  postgres:
    image: postgres:14-alpine
    container_name: trading_postgres
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-trading_password}
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trading_network

  influxdb:
    image: influxdb:2.6-alpine
    container_name: trading_influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-influxdb_password}
      - DOCKER_INFLUXDB_INIT_ORG=trading
      - DOCKER_INFLUXDB_INIT_BUCKET=trading_data
    networks:
      - trading_network

  grafana:
    image: grafana/grafana:9.4.7
    container_name: trading_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-grafana_password}
    depends_on:
      - influxdb
    networks:
      - trading_network

volumes:
  redis_data:
  postgres_data:
  influxdb_data:
  grafana_data:

networks:
  trading_network: